### PR TITLE
Keep a certain amount of BAD_ITEMS and pokemon after recycling

### PR DESCRIPTION
**Pull request by joychugh**

### CODE REVIEW

**Comment by joychugh** [comment]
@j-e-k removed the conflicts

**Comment by j-e-k** [comment]
Will take a look at this later, thanks!

**Comment by j-e-k** [comment]
Can you rebase this to eliminate conflicts? Would be much appreciated

**Comment by joychugh** [comment]
Evolution works, the method name was missing `pokemon`

**Comment by j-e-k** [comment]
Thanks again for catching that!

**Pull request merged**
