### PR TITLE
Ghetto Autosnipe, filtering, pokesnipers.com

### PR DESCRIPTION
**Pull request by Infobesity**
SNIPER

ENABLE master toggle, set to true if you want to snipe pokemon across the world
SNIPING MODE 0 is location mode, catch rarest pokemon at a location, 1 is pokemon mode, sort database for the pokemons you want to catch
SNIPING_MODES modes explained above
TARGET_POKEMON Pokemon you want to snipe, will ignore the rest ["DRAGONITE","OTHER","MEW2KING"] etc
POKEMON_CP_REQ ONLY FOR POKEMON MODE, minimum CP requirement
POKEMON_IV_REQ ONLY FOR POKEMON MODE, minimum IV requirement
USE_POKESNIPERS.COM use pokesnipers.com database, note they use cloudflare, your access token is 30 minutes or so, not too sure but will find a fix later

### CODE REVIEW

**Comment by cryzies** [comment]
@j-e-k could we prioritize pushing an update to master/develop so they passively post pokemon encounters? We can sort out the encountering and sniping in the autosnipe branch. Getting a lot of empty lists from the current database.

**Comment by j-e-k** [comment]
@cryzies Once @destiny117 #460 lands we can merge in those changes into develop. Will take a look at this in a few

**Comment by j-e-k** [comment]
Sadly we are going to have to redo the autosniping given the new refactor, shouldn't be that bad but I will probably start working in dev branch so that we can start collecting more data...what do you think?

**Comment by cryzies** [comment]
@j-e-k, fine by me, just wanted to get the logic down. Transcribing should be easier.

**Pull request closed without merging**
