### PR TITLE
Should we use anything from tomthebotter's copy

### PR DESCRIPTION
**Pull request by sontek**
There seems to be a lot of weird changes, but there might be some good stuff in here as well.. Just opening this PR up so we can review/discuss.

### CODE REVIEW

**Comment by j-e-k** [comment]
I don't see any substantive changes from a quick glance but I could be very mistaken! Looks mostly like pieces of the code base from different points in time (with slight changes to style, etc?)

IF you see anything please add a comment in the commit so I can check it out.

Thanks 😄

**Comment by sontek** [comment]
@j-e-k The one thing he added recently in the configuration which is kind of nice is it returning to start position after so much distance.  That way you don't wander the world but stay close to a certain area (i.e if you like water pokemon... staying close to that)

**Comment by sontek** [comment]
I'm just going to close this and start working off your codebase to add the features I want :)

**Comment by beeedy** [comment]
@sontek, the ability to have it return to a specific location is very nice to also avoid softbans and is probably a worthwhile addition. 

I had an addition that added the ability to automatically transfer duplicate pokemon for those of us more interested in collecting a variety and not necessarily the strongest possible set. I have made some changes and submitted a PR for this specifically
https://github.com/j-e-k/pgoapi/pull/80

**Comment by j-e-k** [comment]
The return to specific location was recently added by @wesselvdv I believe In #63 

Haven't checked it out myself yet though

**Pull request closed without merging**
