### PR TITLE
Added Weedle and Caterpie to the evolve list because they are 12 can…

### PR DESCRIPTION
**Pull request by paulsena**
…dy evolves

### CODE REVIEW

**Comment by joychugh** [comment]
we can add more than 12 ones like Zubat and Drowsezee too, can you add that too?

**Comment by CyriouslyDylan** [comment]
Zubat and Rattata are 25, and Drowze is 50. The 25 candy pokemon should definitely be added though.

**Comment by joychugh** [comment]
Drowzee is so common that we can evolve it even if its 50. Unless someone really loves their Drowzees :)

**Comment by Jay1** [comment]
I think a lot of grinding is done in central park and around NYC, it's really heavy in Zubats over there, I think it would be a great idea to add them even if it's 50 candies.

**Comment by venounan** [comment]
I think a configurable list of them would be best. Some people don't get drowze's at all and would want to keep theirs instead of evolving. Or maybe you're saving candies to power up a certain pokemon.

**Comment by wesselvdv** [comment]
You can pull this request. See #59

**Comment by j-e-k** [comment]
A configurable method for the evolve list has been merged 😄

**Pull request closed without merging**
