### PR TITLE
Dashboard Styles

### PR DESCRIPTION
**Pull request by 0x539**
Added bootstrap and beautified the template.

Added sortable table columns.

Click map to activate controls.

SS of dash: http://imgur.com/a/R22BH

Hope this is right.

### CODE REVIEW

**Comment by 0x539** [comment]
I swear i clicked develop

**Comment by joychugh** [comment]
I made a mistake to merge this since it was going to master but its okay, i merged master to dev but usually if there is a Pull reuest please make it to develop branch of pgoapi

**Comment by 0x539** [comment]
Yea sorry about that. I was sure i changed both to develop. I guess not though.

**Comment by joychugh** [comment]
This looks really awesome!!!  dang

**Pull request merged**
