### PR TITLE
Proxy implementation

### PR DESCRIPTION
**Pull request by vmunich**
- Adds support for proxying bot and PTC auth through a basic proxy.
- Adds argument -p/—proxy to specify a proxy in the proxy_ip:port
  format.  Example:

`python pokecli.py -i 0 -p 123.123.123.123:1234`

Socks proxy:
`python pokecli.py -i 0 -p socks5://123.123.123.123:9191`

### CODE REVIEW

**Comment by vmunich** [comment]
Should login also be done using the proxy? I implemented proxy login for ptc, but since google login uses an installed package `gpsoauth` I didn't implement it for google accounts.

**Comment by BoBeR182** [comment]
Any luck supporting SOCKS5 in the future for Tor.

**Comment by vmunich** [comment]
SOCKS5 is already supported. Example:

`python pokecli.py -i 0 -p socks5://123.123.123.123:9191`

**Comment by j-e-k** [comment]
Can you rebase so we can get this merged? Thanks!

**Comment by vmunich** [comment]
Gonna work on it tonight :)

**Comment by rirze** [comment]
The Readme is missing some critical sections...

**Comment by zambahacker** [comment]
why this not work on google based account ?

**Comment by vmunich** [comment]
@rirze I didn't mean to update the PR, my apologies, I misclicked "sync" on Github Desktop! Since there were a lot of changes in the refactor of the bot, I'm implementing proxies from scratch again rather than updating this PR. 

@zambahacker It will work with Google accounts, but I need to modify the package `gpsoauth`'s  source code.

**Comment by zambahacker** [comment]
@vmunich When you implement google account?

**Comment by vmunich** [comment]
I'm closing this PR and will submit a new one that accounts for the refactor.

**Pull request closed without merging**
