### PR TITLE
fix logic bug with prefer IV setting

### PR DESCRIPTION
**Pull request by magnetik89**

### CODE REVIEW

**Comment by infinitewarp** [comment]
Thanks for breaking my pull request... I already had a better fix outgoing.

**Comment by magnetik89** [comment]
haha, sorry didn't notice

**Comment by stolencatkarma** [comment]
@infinitewarp you can always get on slack and let people know what you're working on. I'm not sure why you don't want to communicate with the rest of us..

**Comment by infinitewarp** [comment]
@stolencatkarma I had [already said that I had a fix coming](https://github.com/j-e-k/poketrainer/issues/564#issue-171074699) when I entered the bug that presumably prompted this commit. I think "I'm working on a fix now" is a pretty good indication of what I'm working on.

**Pull request merged**
