### PR TITLE
Feature/web user list

### PR DESCRIPTION
**Pull request by azgul**
Display an overview of accounts in root (http://127.0.0.1:5000):
http://s.lars.io/20160729201413_ranq4ffpve.png

### CODE REVIEW

**Comment by mdjong1** [comment]
I'd recommend replacing é with `&eacute;`
Also, the users.html appears to be missing a > at the end

**Comment by mdjong1** [comment]
Not sure if this is a general issue, or system-based, but, for me this didn't work:
`
for file_path in data_files:
      match = re.search('\/([^\.]+)\.', file_path)
      if match:
          user_data = get_player_data(match.group()[1:-1])
          users.append(user_data)
`
So I replaced it with this, and it functions (for me) now
`
for file in os.listdir("data_dumps"):
        if file.endswith(".json"):
            user_data = get_player_data(os.path.splitext(file)[0])
            users.append(user_data)
`

**Comment by azgul** [comment]
@mdjong1 https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code ;)

@LarsDR will test it with your way of getting the usernames on Ubuntu

**Comment by j-e-k** [comment]
You are probably going to want to switch to using `.listeners` to get the usernames, since my goal is to get rid of any use of datadumps....

**Comment by LarsDR** [comment]
@j-e-k I've actually just discussed this with @azgul, and will see if I can fix it now.

Out of curiosity, when removing the data_dumps-files, where will you be storing the user data? And will you be creating an api to access it?

**Comment by LarsDR** [comment]
Phew, got this working again now, with the latest develop-branch :-)

**Comment by azgul** [comment]
Fixed the conflicts that arose during the night

**Comment by j-e-k** [comment]
Sorry haven't gotten a chance to look at this, will do shortly :sleepy:

**Comment by j-e-k** [comment]
What do people think about this? I haven't really been totally up to date on what the overall plans are for the web api. Last I heard someone wanted to use angular/react/or something. Do you guys wants to get this merged in the meantime?

**Comment by LarsDR** [comment]
@j-e-k I've taken the endpoint I implemented for this, and moved to the new web ui fork. But for now I think this still makes sense in the current version, until we've finished up the new UI.

**Comment by LarsDR** [comment]
Solved the merge conflicts, but I'm getting an exception when trying to call `c.get_player_info()`.

**Comment by jolbol1** [comment]
Any way to add a stop start button to this web page?

**Comment by LarsDR** [comment]
@jolbol1 If it's possible to start/stop the bot using commands in web.py, then it's doable.

@j-e-k I'm the one developing the new UI as well, along with another guy :-) So this is still relevant, for now.

**Comment by jolbol1** [comment]
Also on the version I'm using it appears to miss out the .com of the username when clicked, thus the UTL is just @gmail

**Comment by matlink** [comment]
Could it be implemented in the master with the listeners?

**Pull request closed without merging**
