### PR TITLE
lessen time output, dont care about date or milliseconds

### PR DESCRIPTION
**Pull request by skydrome**
everything lines up now and the time string doesnt take up half the screen
`20:42:45 [poke_catcher] [ INFO]`
`20:42:48 [ fort_walker] [ INFO]`
`20:42:50 [ poketrainer] [ INFO]`

### CODE REVIEW

**Comment by skydrome** [comment]
everything lines up now and the time string doesnt take up half the screen
`20:42:45 [poketrainer] [ INFO]`
`20:42:48 [fort_walker] [ INFO]`
`20:42:50 [poketrainer] [ INFO]`

**Comment by infinitewarp** [comment]
ms are probably fine to drop, but it's pretty standard practice for CLI tools to log using the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard format (or a variant using ` `instead of`T`for time delimiting) for their timestamps. If you don't want to see some parts, trimming on your end is easy enough at runtime by redirecting output through another program like`cut`or`grep`, but leaving them out entirely means the people that _do_ want the full timestamp have no options.

**Comment by skydrome** [comment]
if someone is saving their pokemon bot logs to disk and looking through them, a month, a year from now, those people need more help than we can provide

**Comment by infinitewarp** [comment]
Well, you could say the same about pretty much _any_ program that produces logs with short-lived meaningfulness. That doesn't mean the standard practice is any less proper to follow.

Besides, we shouldn't underestimate the potential of mining logs at a later date. I'm optimistic that this bot will still be around in the weeks and months to come. Who knows… maybe some clever individual might write, for example, a script to scrape logs to visualize the journey of her bot, growth of characters, etc.

**Comment by jekirl** [comment]
Agreed with @infinitewarp, we should stick to ISO-8601 for all logs

**Pull request closed without merging**
